import React, { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";
import styled, { keyframes } from "styled-components";

// Initialize mermaid with dark theme settings
mermaid.initialize({
  startOnLoad: false,
  theme: "dark",
  securityLevel: "loose",
  themeVariables: {
    primaryColor: "#7c3aed",
    primaryTextColor: "#e2e8f0",
    primaryBorderColor: "#8b5cf6",
    lineColor: "#a78bfa",
    secondaryColor: "#1e1b4b",
    tertiaryColor: "#312e81",
    background: "#1a1a2e",
    mainBkg: "#1e1b4b",
    nodeBorder: "#8b5cf6",
    clusterBkg: "#1e1b4b",
    clusterBorder: "#7c3aed",
    titleColor: "#e2e8f0",
    edgeLabelBackground: "#312e81",
    actorBorder: "#8b5cf6",
    actorBkg: "#1e1b4b",
    actorTextColor: "#e2e8f0",
    actorLineColor: "#a78bfa",
    signalColor: "#e2e8f0",
    signalTextColor: "#e2e8f0",
    labelBoxBkgColor: "#1e1b4b",
    labelBoxBorderColor: "#7c3aed",
    labelTextColor: "#e2e8f0",
    loopTextColor: "#e2e8f0",
    noteBorderColor: "#7c3aed",
    noteBkgColor: "#312e81",
    noteTextColor: "#e2e8f0",
    activationBorderColor: "#8b5cf6",
    activationBkgColor: "#1e1b4b",
    sequenceNumberColor: "#e2e8f0",
  },
  flowchart: {
    htmlLabels: true,
    curve: "basis",
  },
  sequence: {
    diagramMarginX: 50,
    diagramMarginY: 10,
    actorMargin: 50,
    width: 150,
    height: 65,
    boxMargin: 10,
    boxTextMargin: 5,
    noteMargin: 10,
    messageMargin: 35,
    mirrorActors: true,
    useMaxWidth: true,
  },
});

interface MermaidDiagramProps {
  chart: string;
}

const pulse = keyframes`
  0%, 100% { opacity: 0.5; }
  50% { opacity: 1; }
`;

const DiagramContainer = styled.div`
  margin: 16px 0;
  padding: 20px;
  background: linear-gradient(135deg, rgba(30, 27, 75, 0.8) 0%, rgba(49, 46, 129, 0.6) 100%);
  border-radius: 12px;
  border: 1px solid rgba(139, 92, 246, 0.3);
  overflow-x: auto;
  
  &:hover {
    border-color: rgba(139, 92, 246, 0.5);
    box-shadow: 0 0 20px rgba(124, 58, 237, 0.2);
  }

  /* Style the SVG generated by mermaid */
  svg {
    max-width: 100%;
    height: auto;
  }

  .error {
    color: #f87171;
    padding: 16px;
    background: rgba(248, 113, 113, 0.1);
    border-radius: 8px;
    border: 1px solid rgba(248, 113, 113, 0.3);
  }
`;

const DiagramHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid rgba(139, 92, 246, 0.2);
`;

const DiagramLabel = styled.span`
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 1px;
  color: #a78bfa;
`;

const DiagramIcon = styled.span`
  font-size: 16px;
`;

const CopyButton = styled.button<{ $copied: boolean }>`
  padding: 6px 12px;
  background: ${props => props.$copied 
    ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
    : 'rgba(139, 92, 246, 0.2)'
  };
  color: ${props => props.$copied ? '#fff' : '#a78bfa'};
  border: 1px solid ${props => props.$copied 
    ? 'rgba(16, 185, 129, 0.5)'
    : 'rgba(139, 92, 246, 0.3)'
  };
  border-radius: 6px;
  cursor: pointer;
  font-size: 11px;
  font-weight: 500;
  transition: all 0.2s ease;

  &:hover {
    background: ${props => props.$copied 
      ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
      : 'rgba(139, 92, 246, 0.3)'
    };
  }
`;

const LoadingState = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
  color: #a78bfa;
  font-size: 14px;
  animation: ${pulse} 1.5s ease-in-out infinite;
`;

const ErrorState = styled.div`
  padding: 16px;
  background: rgba(248, 113, 113, 0.1);
  border-radius: 8px;
  border: 1px solid rgba(248, 113, 113, 0.3);
  color: #f87171;
  font-size: 13px;
`;

const ErrorMessage = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
  font-weight: 600;
`;

const ErrorDetails = styled.pre`
  margin: 8px 0;
  padding: 12px;
  background: rgba(0, 0, 0, 0.3);
  border-radius: 6px;
  overflow-x: auto;
  font-size: 12px;
  color: #fca5a5;
  white-space: pre-wrap;
  word-break: break-word;
`;

const CodeToggle = styled.button`
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 12px;
  padding: 8px 12px;
  background: rgba(139, 92, 246, 0.15);
  border: 1px solid rgba(139, 92, 246, 0.3);
  border-radius: 6px;
  color: #a78bfa;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background: rgba(139, 92, 246, 0.25);
    border-color: rgba(139, 92, 246, 0.5);
  }
`;

const RawCode = styled.pre`
  margin-top: 12px;
  padding: 16px;
  background: rgba(20, 20, 35, 0.8);
  border-radius: 8px;
  border: 1px solid rgba(139, 92, 246, 0.2);
  overflow-x: auto;
  font-size: 12px;
  line-height: 1.6;
  color: #e2e8f0;
  font-family: 'Fira Code', 'Consolas', monospace;

  .keyword {
    color: #c792ea;
  }
  .arrow {
    color: #89ddff;
  }
  .node {
    color: #82aaff;
  }
  .text {
    color: #c3e88d;
  }
`;

export const MermaidDiagram: React.FC<MermaidDiagramProps> = ({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [showRawCode, setShowRawCode] = useState(false);

  // Minimal sanitization - the code should now come through cleanly via base64
  const sanitizeMermaidCode = (code: string): string => {
    let sanitized = code;
    
    // Only decode any remaining HTML entities (shouldn't be many now)
    sanitized = sanitized.replace(/&amp;/g, '&');
    sanitized = sanitized.replace(/&lt;/g, '<');
    sanitized = sanitized.replace(/&gt;/g, '>');
    sanitized = sanitized.replace(/&quot;/g, '"');
    sanitized = sanitized.replace(/&#39;/g, "'");
    
    // Normalize line endings
    sanitized = sanitized.replace(/\r\n/g, '\n');
    sanitized = sanitized.replace(/\r/g, '\n');
    
    return sanitized.trim();
  };

  // Auto-fix common LLM mermaid syntax errors
  const autoFixMermaidCode = (code: string): string[] => {
    const fixes: string[] = [];
    
    // Fix 1: Replace & with 'and' in labels (very common LLM error)
    if (code.includes('&')) {
      const fixed = code.replace(/(\w)\s*&\s*(\w)/g, '$1 and $2');
      if (fixed !== code) fixes.push(fixed);
    }
    
    // Fix 2: Remove problematic characters from labels
    const fixedChars = code
      .replace(/[""'']/g, '"') // Smart quotes to regular
      .replace(/–/g, '-') // En-dash to hyphen
      .replace(/—/g, '-') // Em-dash to hyphen
      .replace(/…/g, '...'); // Ellipsis
    if (fixedChars !== code) fixes.push(fixedChars);
    
    // Fix 3: Fix unbalanced brackets in node definitions
    const lines = code.split('\n');
    const fixedLines = lines.map(line => {
      // Count brackets
      const openSquare = (line.match(/\[/g) || []).length;
      const closeSquare = (line.match(/\]/g) || []).length;
      const openParen = (line.match(/\(/g) || []).length;
      const closeParen = (line.match(/\)/g) || []).length;
      const openCurly = (line.match(/\{/g) || []).length;
      const closeCurly = (line.match(/\}/g) || []).length;
      
      let fixedLine = line;
      // Add missing closing brackets
      if (openSquare > closeSquare) fixedLine += ']'.repeat(openSquare - closeSquare);
      if (openParen > closeParen) fixedLine += ')'.repeat(openParen - closeParen);
      if (openCurly > closeCurly) fixedLine += '}'.repeat(openCurly - closeCurly);
      
      return fixedLine;
    });
    const bracketFixed = fixedLines.join('\n');
    if (bracketFixed !== code) fixes.push(bracketFixed);
    
    // Fix 4: Fix sequence diagram specific issues
    if (code.includes('sequenceDiagram')) {
      // Fix missing colons after participant/actor
      let seqFixed = code.replace(/^(\s*(?:participant|actor)\s+\w+)\s*$/gm, '$1');
      // Fix Note syntax
      seqFixed = seqFixed.replace(/Note\s+over\s+/gi, 'Note over ');
      seqFixed = seqFixed.replace(/Note\s+left\s+of\s+/gi, 'Note left of ');
      seqFixed = seqFixed.replace(/Note\s+right\s+of\s+/gi, 'Note right of ');
      if (seqFixed !== code) fixes.push(seqFixed);
    }
    
    // Fix 5: Fix flowchart specific issues
    if (code.includes('flowchart') || code.includes('graph')) {
      // Fix arrow syntax issues
      let flowFixed = code
        .replace(/-->\|([^|]+)\|>/g, '-->|$1|') // Remove extra > after label
        .replace(/-+>/g, '-->') // Normalize arrows
        .replace(/=+>/g, '==>'); // Normalize thick arrows
      if (flowFixed !== code) fixes.push(flowFixed);
    }
    
    // Fix 6: Fix classDiagram issues
    if (code.includes('classDiagram')) {
      let classFixed = code
        .replace(/:\s*\+/g, ': +') // Ensure space before visibility
        .replace(/:\s*-/g, ': -')
        .replace(/:\s*#/g, ': #');
      if (classFixed !== code) fixes.push(classFixed);
    }
    
    // Fix 7: Remove any HTML tags that might have leaked in
    const noHtml = code.replace(/<[^>]+>/g, '');
    if (noHtml !== code) fixes.push(noHtml);
    
    // Fix 8: Combine multiple fixes
    let combinedFix = code
      .replace(/(\w)\s*&\s*(\w)/g, '$1 and $2')
      .replace(/[""'']/g, '"')
      .replace(/–/g, '-')
      .replace(/—/g, '-')
      .replace(/<[^>]+>/g, '');
    
    // Also fix brackets in combined
    const combinedLines = combinedFix.split('\n').map(line => {
      const openSquare = (line.match(/\[/g) || []).length;
      const closeSquare = (line.match(/\]/g) || []).length;
      if (openSquare > closeSquare) return line + ']'.repeat(openSquare - closeSquare);
      return line;
    });
    combinedFix = combinedLines.join('\n');
    
    if (combinedFix !== code) fixes.push(combinedFix);
    
    // Remove duplicates and the original code
    return [...new Set(fixes)].filter(f => f !== code);
  };

  useEffect(() => {
    const renderDiagram = async () => {
      if (!chart || !containerRef.current) return;

      setIsLoading(true);
      setError("");
      setSvg("");

      const cleanChart = sanitizeMermaidCode(chart);
      
      // Try to render with auto-fix attempts
      const tryRender = async (code: string): Promise<{ success: boolean; svg?: string; error?: string }> => {
        try {
          const id = `mermaid-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          const { svg: renderedSvg } = await mermaid.render(id, code);
          return { success: true, svg: renderedSvg };
        } catch (err) {
          return { success: false, error: err instanceof Error ? err.message : String(err) };
        }
      };

      // First attempt with original code
      let result = await tryRender(cleanChart);
      
      if (!result.success) {
        console.log('Mermaid: Initial render failed, attempting auto-fix...');
        
        // Get potential fixes
        const fixes = autoFixMermaidCode(cleanChart);
        
        // Try each fix
        for (const fix of fixes) {
          console.log('Mermaid: Trying auto-fix variant...');
          result = await tryRender(fix);
          if (result.success) {
            console.log('Mermaid: Auto-fix successful!');
            break;
          }
        }
      }

      if (result.success && result.svg) {
        setSvg(result.svg);
      } else {
        console.error("Mermaid rendering error (all fixes failed):", result.error);
        setError(result.error || "Failed to render diagram");
      }
      
      setIsLoading(false);
    };

    renderDiagram();
  }, [chart]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(chart);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  // Simple syntax highlighting for Mermaid code
  const highlightMermaidCode = (code: string): string => {
    return code
      // Highlight diagram type keywords
      .replace(/^(flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|gantt|pie|journey|gitGraph|mindmap|timeline|sankey|block|architecture)/gm, 
        '<span class="keyword">$1</span>')
      // Highlight direction keywords
      .replace(/\b(TD|TB|BT|RL|LR|participant|actor|Note|loop|alt|else|end|opt|par|critical|break)\b/g, 
        '<span class="keyword">$1</span>')
      // Highlight arrows
      .replace(/(-->|--o|--x|-.->|-.-|==>|==|---|\|>|<\||--\||&gt;|&lt;)/g, 
        '<span class="arrow">$1</span>')
      // Highlight node IDs (before brackets)
      .replace(/\b([A-Z][a-zA-Z0-9_]*)\s*[\[\{\(]/g, 
        '<span class="node">$1</span>[');
  };

  return (
    <DiagramContainer ref={containerRef}>
      <DiagramHeader>
        <DiagramLabel>
          <DiagramIcon>📊</DiagramIcon>
          Mermaid Diagram
        </DiagramLabel>
        <CopyButton onClick={handleCopy} $copied={copied}>
          {copied ? "Copied!" : "Copy Code"}
        </CopyButton>
      </DiagramHeader>

      {isLoading && <LoadingState>Rendering diagram...</LoadingState>}
      
      {error && (
        <ErrorState>
          <ErrorMessage>
            <span>⚠️</span>
            <span>Diagram Syntax Error</span>
          </ErrorMessage>
          <p style={{ marginBottom: '8px', color: '#fca5a5' }}>
            The LLM generated invalid Mermaid syntax. The diagram could not be rendered.
          </p>
          <ErrorDetails>{error}</ErrorDetails>
          
          <CodeToggle onClick={() => setShowRawCode(!showRawCode)}>
            <span>{showRawCode ? '▼' : '▶'}</span>
            <span>{showRawCode ? 'Hide' : 'Show'} Raw Diagram Code</span>
          </CodeToggle>
          
          {showRawCode && (
            <RawCode dangerouslySetInnerHTML={{ __html: highlightMermaidCode(chart) }} />
          )}
        </ErrorState>
      )}
      
      {svg && !error && (
        <>
          <div dangerouslySetInnerHTML={{ __html: svg }} />
          
          {/* Collapsible raw code section for reference */}
          <CodeToggle onClick={() => setShowRawCode(!showRawCode)} style={{ marginTop: '16px' }}>
            <span>{showRawCode ? '▼' : '▶'}</span>
            <span>{showRawCode ? 'Hide' : 'Show'} Source Code</span>
          </CodeToggle>
          
          {showRawCode && (
            <RawCode dangerouslySetInnerHTML={{ __html: highlightMermaidCode(chart) }} />
          )}
        </>
      )}
    </DiagramContainer>
  );
};

export default MermaidDiagram;
