import React, { useEffect, useMemo, useRef, useState } from "react";
import mermaid from "mermaid";
import styled, { keyframes } from "styled-components";

// Initialize mermaid with dark theme settings
mermaid.initialize({
  startOnLoad: false,
  theme: "dark",
  securityLevel: "strict",
  themeVariables: {
    primaryColor: "#7c3aed",
    primaryTextColor: "#e2e8f0",
    primaryBorderColor: "#8b5cf6",
    lineColor: "#a78bfa",
    secondaryColor: "#1e1b4b",
    tertiaryColor: "#312e81",
    background: "#1a1a2e",
    mainBkg: "#1e1b4b",
    nodeBorder: "#8b5cf6",
    clusterBkg: "#1e1b4b",
    clusterBorder: "#7c3aed",
    titleColor: "#e2e8f0",
    edgeLabelBackground: "#312e81",
    actorBorder: "#8b5cf6",
    actorBkg: "#1e1b4b",
    actorTextColor: "#e2e8f0",
    actorLineColor: "#a78bfa",
    signalColor: "#e2e8f0",
    signalTextColor: "#e2e8f0",
    labelBoxBkgColor: "#1e1b4b",
    labelBoxBorderColor: "#7c3aed",
    labelTextColor: "#e2e8f0",
    loopTextColor: "#e2e8f0",
    noteBorderColor: "#7c3aed",
    noteBkgColor: "#312e81",
    noteTextColor: "#e2e8f0",
    activationBorderColor: "#8b5cf6",
    activationBkgColor: "#1e1b4b",
    sequenceNumberColor: "#e2e8f0",
  },
  flowchart: {
    htmlLabels: false,
    curve: "basis",
  },
  sequence: {
    diagramMarginX: 50,
    diagramMarginY: 10,
    actorMargin: 50,
    width: 150,
    height: 65,
    boxMargin: 10,
    boxTextMargin: 5,
    noteMargin: 10,
    messageMargin: 35,
    mirrorActors: true,
    useMaxWidth: true,
  },
});

interface MermaidDiagramProps {
  chart: string;
}

const pulse = keyframes`
  0%, 100% { opacity: 0.5; }
  50% { opacity: 1; }
`;

const DiagramContainer = styled.div`
  margin: 16px 0;
  padding: 20px;
  background: linear-gradient(135deg, rgba(30, 27, 75, 0.8) 0%, rgba(49, 46, 129, 0.6) 100%);
  border-radius: 12px;
  border: 1px solid rgba(139, 92, 246, 0.3);
  overflow-x: auto;
  
  &:hover {
    border-color: rgba(139, 92, 246, 0.5);
    box-shadow: 0 0 20px rgba(124, 58, 237, 0.2);
  }

  /* Style the SVG generated by mermaid */
  svg {
    max-width: 100%;
    height: auto;
  }

  .error {
    color: #f87171;
    padding: 16px;
    background: rgba(248, 113, 113, 0.1);
    border-radius: 8px;
    border: 1px solid rgba(248, 113, 113, 0.3);
  }
`;

const DiagramHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid rgba(139, 92, 246, 0.2);
`;

const DiagramLabel = styled.span`
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 1px;
  color: #a78bfa;
`;

const DiagramIcon = styled.span`
  font-size: 16px;
`;

const CopyButton = styled.button<{ $copied: boolean }>`
  padding: 6px 12px;
  background: ${props => props.$copied 
    ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
    : 'rgba(139, 92, 246, 0.2)'
  };
  color: ${props => props.$copied ? '#fff' : '#a78bfa'};
  border: 1px solid ${props => props.$copied 
    ? 'rgba(16, 185, 129, 0.5)'
    : 'rgba(139, 92, 246, 0.3)'
  };
  border-radius: 6px;
  cursor: pointer;
  font-size: 11px;
  font-weight: 500;
  transition: all 0.2s ease;

  &:hover {
    background: ${props => props.$copied 
      ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
      : 'rgba(139, 92, 246, 0.3)'
    };
  }
`;

const LoadingState = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
  color: #a78bfa;
  font-size: 14px;
  animation: ${pulse} 1.5s ease-in-out infinite;
`;

const ErrorState = styled.div`
  padding: 16px;
  background: rgba(248, 113, 113, 0.1);
  border-radius: 8px;
  border: 1px solid rgba(248, 113, 113, 0.3);
  color: #f87171;
  font-size: 13px;
`;

const ErrorMessage = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
  font-weight: 600;
`;

const ErrorDetails = styled.pre`
  margin: 8px 0;
  padding: 12px;
  background: rgba(0, 0, 0, 0.3);
  border-radius: 6px;
  overflow-x: auto;
  font-size: 12px;
  color: #fca5a5;
  white-space: pre-wrap;
  word-break: break-word;
`;

const CodeToggle = styled.button`
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 12px;
  padding: 8px 12px;
  background: rgba(139, 92, 246, 0.15);
  border: 1px solid rgba(139, 92, 246, 0.3);
  border-radius: 6px;
  color: #a78bfa;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background: rgba(139, 92, 246, 0.25);
    border-color: rgba(139, 92, 246, 0.5);
  }
`;

const RawCode = styled.div`
  margin-top: 12px;
  background: rgba(13, 16, 34, 0.92);
  border-radius: 10px;
  border: 1px solid rgba(139, 92, 246, 0.25);
  overflow: hidden;
  box-shadow: inset 0 1px 0 rgba(124, 58, 237, 0.12);

  .keyword {
    color: #c792ea;
  }
  .arrow {
    color: #89ddff;
  }
  .node {
    color: #82aaff;
  }
  .text {
    color: #c3e88d;
  }
  .comment {
    color: #6ee7b7;
  }
`;

const RawCodeMeta = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  background: linear-gradient(135deg, rgba(76, 29, 149, 0.55) 0%, rgba(30, 64, 175, 0.35) 100%);
  border-bottom: 1px solid rgba(139, 92, 246, 0.25);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  color: #c4b5fd;
`;

const RawCodeBadge = styled.span`
  display: inline-flex;
  align-items: center;
  gap: 6px;
  background: rgba(55, 48, 163, 0.6);
  border: 1px solid rgba(139, 92, 246, 0.4);
  border-radius: 999px;
  padding: 4px 10px;
  font-size: 10px;
  letter-spacing: 0.08em;
  color: #e0e7ff;
`;

const RawCodeContent = styled.div`
  max-height: 360px;
  overflow: auto;
  padding: 14px 0;
  font-family: 'Fira Code', 'Consolas', monospace;
  font-size: 12px;
  color: #e2e8f0;

  .code-lines {
    display: grid;
    row-gap: 4px;
    padding: 0 16px 8px 16px;
  }

  .code-line {
    display: grid;
    grid-template-columns: 44px 1fr;
    gap: 12px;
    align-items: start;
  }

  .code-line-number {
    position: relative;
    display: inline-flex;
    justify-content: flex-end;
    color: rgba(129, 140, 248, 0.9);
    font-variant-numeric: tabular-nums;
    padding-right: 12px;
    border-right: 1px solid rgba(99, 102, 241, 0.2);
  }

  .code-line-text {
    white-space: pre;
    line-height: 1.5;
  }
`;

const formatMermaidCode = (code: string): { html: string; lineCount: number } => {
  const escapeHtml = (value: string): string =>
    value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');

  const diagramKeywordPattern = /(flowchart|sequenceDiagram|classDiagram|stateDiagram(?:-v\d+)?|erDiagram|gantt|pie|journey|gitGraph|mindmap|timeline|sankey|block|architecture)/g;
  const directivePattern = /(direction|TD|TB|BT|RL|LR|participant|actor|Note|loop|alt|else|end|opt|par|critical|break|state)/g;
  const escapeRegex = (token: string) => token.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const arrowTokens = ['--&gt;', '==&gt;', '&lt;--', '-o-&gt;', '-x-&gt;', '-.-&gt;', '--o', '--x', '--|', '|--', '|&gt;', '&lt;|', '===', '---', '=='];
  const arrowPattern = new RegExp(`(${arrowTokens.map(escapeRegex).join('|')})`, 'g');
  const startStopPattern = /\[\*\]/g;

  const highlightLine = (line: string): string => {
    const escaped = escapeHtml(line);

    if (/^\s*%%/.test(line)) {
      return `<span class="comment">${escaped}</span>`;
    }

    let highlighted = escaped;
    highlighted = highlighted.replace(diagramKeywordPattern, '<span class="keyword">$1</span>');
    highlighted = highlighted.replace(directivePattern, '<span class="keyword">$1</span>');
    highlighted = highlighted.replace(arrowPattern, '<span class="arrow">$1</span>');
    highlighted = highlighted.replace(startStopPattern, '<span class="arrow">$&</span>');
    highlighted = highlighted.replace(/\b([A-Za-z][\w]*)\s*(?=\[|\{|\()/g, '<span class="node">$1</span>');
    highlighted = highlighted.replace(/(\[[^\]]+\])/g, '<span class="text">$1</span>');

    return highlighted;
  };

  const normalized = code.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const lines = normalized.split('\n');
  const htmlLines = lines.map((line, index) => {
    const highlighted = highlightLine(line);
    const display = highlighted.length ? highlighted : '&nbsp;';
    const lineNumber = (index + 1).toString().padStart(3, ' ');
    const safeNumber = lineNumber.replace(/ /g, '&nbsp;');
    return `<div class="code-line"><span class="code-line-number">${safeNumber}</span><span class="code-line-text">${display}</span></div>`;
  });

  return {
    html: `<div class="code-lines">${htmlLines.join('')}</div>`,
    lineCount: lines.length,
  };
};

export const MermaidDiagram: React.FC<MermaidDiagramProps> = ({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [showRawCode, setShowRawCode] = useState(false);
  const formattedCode = useMemo(() => formatMermaidCode(chart), [chart]);
  const lineSummary = `${formattedCode.lineCount} ${formattedCode.lineCount === 1 ? 'line' : 'lines'}`;

  const renderRawCodePanel = () => (
    <RawCode>
      <RawCodeMeta>
        <span>Mermaid Source</span>
        <RawCodeBadge>{lineSummary}</RawCodeBadge>
      </RawCodeMeta>
      <RawCodeContent>
        <div dangerouslySetInnerHTML={{ __html: formattedCode.html }} />
      </RawCodeContent>
    </RawCode>
  );

  // Minimal sanitization - the code should now come through cleanly via base64
  const sanitizeMermaidCode = (code: string): string => {
    let sanitized = code;
    
    // Only decode any remaining HTML entities (shouldn't be many now)
    sanitized = sanitized.replace(/&amp;/g, '&');
    sanitized = sanitized.replace(/&lt;/g, '<');
    sanitized = sanitized.replace(/&gt;/g, '>');
    sanitized = sanitized.replace(/&quot;/g, '"');
    sanitized = sanitized.replace(/&#39;/g, "'");
    
    // Normalize line endings
    sanitized = sanitized.replace(/\r\n/g, '\n');
    sanitized = sanitized.replace(/\r/g, '\n');
    
    return sanitized.trim();
  };

  // Auto-fix common LLM mermaid syntax errors
  const autoFixMermaidCode = (code: string): string[] => {
    const fixes: string[] = [];
    
    // Fix 1: Replace & with 'and' in labels (very common LLM error)
    if (code.includes('&')) {
      const fixed = code.replace(/(\w)\s*&\s*(\w)/g, '$1 and $2');
      if (fixed !== code) fixes.push(fixed);
    }
    
    // Fix 2: Remove problematic characters from labels
    const fixedChars = code
      .replace(/[""'']/g, '"') // Smart quotes to regular
      .replace(/–/g, '-') // En-dash to hyphen
      .replace(/—/g, '-') // Em-dash to hyphen
      .replace(/…/g, '...'); // Ellipsis
    if (fixedChars !== code) fixes.push(fixedChars);
    
    // Fix 3: Fix unbalanced brackets in node definitions
    const lines = code.split('\n');
    const fixedLines = lines.map(line => {
      // Count brackets
      const openSquare = (line.match(/\[/g) || []).length;
      const closeSquare = (line.match(/\]/g) || []).length;
      const openParen = (line.match(/\(/g) || []).length;
      const closeParen = (line.match(/\)/g) || []).length;
      const openCurly = (line.match(/\{/g) || []).length;
      const closeCurly = (line.match(/\}/g) || []).length;
      
      let fixedLine = line;
      // Add missing closing brackets
      if (openSquare > closeSquare) fixedLine += ']'.repeat(openSquare - closeSquare);
      if (openParen > closeParen) fixedLine += ')'.repeat(openParen - closeParen);
      if (openCurly > closeCurly) fixedLine += '}'.repeat(openCurly - closeCurly);
      
      return fixedLine;
    });
    const bracketFixed = fixedLines.join('\n');
    if (bracketFixed !== code) fixes.push(bracketFixed);
    
    // Fix 4: Fix sequence diagram specific issues
    if (code.includes('sequenceDiagram')) {
      // Fix missing colons after participant/actor
      let seqFixed = code.replace(/^(\s*(?:participant|actor)\s+\w+)\s*$/gm, '$1');
      // Fix Note syntax
      seqFixed = seqFixed.replace(/Note\s+over\s+/gi, 'Note over ');
      seqFixed = seqFixed.replace(/Note\s+left\s+of\s+/gi, 'Note left of ');
      seqFixed = seqFixed.replace(/Note\s+right\s+of\s+/gi, 'Note right of ');
      // Remove numbering accidentally appended to end statements
      seqFixed = seqFixed.replace(/end\s*\d+/gi, 'end');
      if (seqFixed !== code) fixes.push(seqFixed);
    }
    
    // Fix 5: Fix flowchart specific issues
    if (code.includes('flowchart') || code.includes('graph')) {
      const flowFixed = code
        // Remove extra > after label arrows
        .replace(/--\|([^|]+)\|>/g, '-->|$1|')
        // Normalize arrows like -> or ---> to -->
        .replace(/-+>/g, '-->')
        // Normalize thick arrows like => or ===>
        .replace(/=+>/g, '==>')
        // Normalize reverse arrows like <- or <---
        .replace(/<-+/g, '<--')
        // Fix circle arrow shorthand -o> to -o->
        .replace(/-o>/g, '-o->')
        // Convert single hyphen edge definitions to proper arrows
        .replace(/^(\s*[A-Za-z0-9_]+)\s*-\s+(\w+)/gm, '$1 --> $2')
        .replace(/^(\s*[A-Za-z0-9_]+)\s*-\s+\|([^|]+)\|\s*(\w+)/gm, '$1 -->|$2| $3')
        // Replace colon direction declarations like "graph: TD" with valid syntax
        .replace(/^(graph|flowchart)\s*:\s*/gm, '$1 ');

      if (flowFixed !== code) fixes.push(flowFixed);
    }
    
    // Fix 6: Fix classDiagram issues
    if (code.includes('classDiagram')) {
      const classFixed = code
        .replace(/:\s*\+/g, ': +') // Ensure space before visibility
        .replace(/:\s*-/g, ': -')
        .replace(/:\s*#/g, ': #');
      if (classFixed !== code) fixes.push(classFixed);
    }
    
    // Fix 7: Remove any HTML tags that might have leaked in
    const noHtml = code.replace(/<[^>]+>/g, '');
    if (noHtml !== code) fixes.push(noHtml);
    
    // Fix 8: Remove duplicated node identifiers appended after definitions (e.g., N[Label]N -->)
    const removeDuplicateNodeIds = code.replace(/([A-Za-z0-9_]+)(\[[^\]]+\])\1/g, '$1$2');
    if (removeDuplicateNodeIds !== code) fixes.push(removeDuplicateNodeIds);

    const fixTrailingNodeAfterBracket = code.replace(/(\[[^\]]+\])[A-Za-z0-9_]+(\s*-->|\s*$)/g, '$1$2');
    if (fixTrailingNodeAfterBracket !== code) fixes.push(fixTrailingNodeAfterBracket);

    // Fix 9: Combine multiple fixes
    let combinedFix = code
      .replace(/(\w)\s*&\s*(\w)/g, '$1 and $2')
      .replace(/[""'']/g, '"')
      .replace(/–/g, '-')
      .replace(/—/g, '-')
      .replace(/<[^>]+>/g, '');
    
    // Also fix brackets in combined
    const combinedLines = combinedFix.split('\n').map(line => {
      const openSquare = (line.match(/\[/g) || []).length;
      const closeSquare = (line.match(/\]/g) || []).length;
      if (openSquare > closeSquare) return line + ']'.repeat(openSquare - closeSquare);
      return line;
    });
    combinedFix = combinedLines.join('\n');
    
    if (combinedFix !== code) fixes.push(combinedFix);

    // Fix 10: Replace semicolon separators with newlines for flowcharts/sequence diagrams
    const semicolonSplit = code.replace(/;\s*/g, '\n');
    if (semicolonSplit !== code) fixes.push(semicolonSplit);

    // Fix 11: Remove numbered list prefixes (e.g., "1.", "2)") that break syntax
    const numberStripped = code
      .split('\n')
      .map(line => line.replace(/^\s*\d+[.)]\s*/, ''))
      .join('\n');
    if (numberStripped !== code) fixes.push(numberStripped);

    // Fix 12: Ensure standalone end statements don't have trailing text
    const cleanEndDigits = code.replace(/\bend\s*\d+\b/gi, 'end');
    if (cleanEndDigits !== code) fixes.push(cleanEndDigits);

    // Fix 13: Merge multiline node labels where bracketed text spilled onto the next line
    // const mergedLabelLines = (() => {
    //   const labelLines = code.split('\n');
    //   const rebuilt: string[] = [];

    //   for (const current of labelLines) {
    //     if (rebuilt.length) {
    //       const previous = rebuilt[rebuilt.length - 1];
    //       const openSquare = (previous.match(/\[/g) || []).length;
    //       const closeSquare = (previous.match(/\]/g) || []).length;
    //       const openCurly = (previous.match(/\{/g) || []).length;
    //       const closeCurly = (previous.match(/\}/g) || []).length;
    //       const openParen = (previous.match(/\(/g) || []).length;
    //       const closeParen = (previous.match(/\)/g) || []).length;

    //       const hasUnclosedBracket = openSquare > closeSquare || openCurly > closeCurly || openParen > closeParen;
    //       const trimmedCurrent = current.trim();
    //       const looksLikeContinuation =
    //         trimmedCurrent.length > 0 &&
    //         !/^\s*[A-Za-z0-9_]+\s*[\[\{\(]/.test(current) &&
    //         !/(-->|==>|<--|\|>|::|:::)/.test(current);

    //       if (hasUnclosedBracket && looksLikeContinuation) {
    //         rebuilt[rebuilt.length - 1] = `${previous.trimEnd()} ${trimmedCurrent}`;
    //         continue;
    //       }
    //     }

    //     rebuilt.push(current);
    //   }

    //   return rebuilt.join('\n');
    // })();
    // if (mergedLabelLines !== code) fixes.push(mergedLabelLines);

    // Remove duplicates and the original code
    return [...new Set(fixes)].filter(f => f !== code);
  };

  useEffect(() => {
    const renderDiagram = async () => {
      if (!chart || !containerRef.current) return;

      setIsLoading(true);
      setError("");
      setSvg("");

      const cleanChart = sanitizeMermaidCode(chart);
      
      // Try to render with auto-fix attempts
      const tryRender = async (code: string): Promise<{ success: boolean; svg?: string; error?: string }> => {
        try {
          const id = `mermaid-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          const { svg: renderedSvg } = await mermaid.render(id, code);
          return { success: true, svg: renderedSvg };
        } catch (err) {
          return { success: false, error: err instanceof Error ? err.message : String(err) };
        }
      };

      // First attempt with original code
      let result = await tryRender(cleanChart);
      
      if (!result.success) {
        console.log('Mermaid: Initial render failed, attempting auto-fix...');
        
        // Get potential fixes
        const fixes = autoFixMermaidCode(cleanChart);
        
        // Try each fix
        for (const fix of fixes) {
          console.log('Mermaid: Trying auto-fix variant...');
          result = await tryRender(fix);
          if (result.success) {
            console.log('Mermaid: Auto-fix successful!');
            break;
          }
        }
      }

      if (result.success && result.svg) {
        setSvg(result.svg);
      } else {
        console.error("Mermaid rendering error (all fixes failed):", result.error);
        setError(result.error || "Failed to render diagram");
      }
      
      setIsLoading(false);
    };

    renderDiagram();
  }, [chart]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(chart);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };
  return (
    <DiagramContainer ref={containerRef}>
      <DiagramHeader>
        <DiagramLabel>
          <DiagramIcon>📊</DiagramIcon>
          Mermaid Diagram
        </DiagramLabel>
        <CopyButton onClick={handleCopy} $copied={copied}>
          {copied ? "Copied!" : "Copy Code"}
        </CopyButton>
      </DiagramHeader>

      {isLoading && <LoadingState>Rendering diagram...</LoadingState>}
      
      {error && (
        <ErrorState>
          <ErrorMessage>
            <span>⚠️</span>
            <span>Diagram Syntax Error</span>
          </ErrorMessage>
          <p style={{ marginBottom: '8px', color: '#fca5a5' }}>
            The LLM generated invalid Mermaid syntax. The diagram could not be rendered.
          </p>
          <ErrorDetails>{error}</ErrorDetails>
          
          <CodeToggle onClick={() => setShowRawCode(!showRawCode)}>
            <span>{showRawCode ? '▼' : '▶'}</span>
            <span>{showRawCode ? 'Hide' : 'Show'} Raw Diagram Code</span>
          </CodeToggle>
          
          {showRawCode && renderRawCodePanel()}
        </ErrorState>
      )}
      
      {svg && !error && (
        <>
          <div dangerouslySetInnerHTML={{ __html: svg }} />
          
          {/* Collapsible raw code section for reference */}
          <CodeToggle onClick={() => setShowRawCode(!showRawCode)} style={{ marginTop: '16px' }}>
            <span>{showRawCode ? '▼' : '▶'}</span>
            <span>{showRawCode ? 'Hide' : 'Show'} Source Code</span>
          </CodeToggle>
          
          {showRawCode && renderRawCodePanel()}
        </>
      )}
    </DiagramContainer>
  );
};

export default MermaidDiagram;
