export const felipecCss = `/*!
 * Theme: FelipeC
 * Author: (c) 2021 Felipe Contreras <felipe.contreras@gmail.com>
 * Website: https://github.com/felipec/vim-felipec
 *
 * Autogenerated with vim-felipec's generator.
*/

.hljs {
  color: #dddde1;
  background: transparent;
}

.hljs::selection,
.hljs ::selection {
  color: #1e1e22;
  background: #bf8fef;
}

.hljs-comment,
.hljs-code,
.hljs-quote {
  color: #888896;
}

.hljs-number,
.hljs-literal,
.hljs-deletion {
  color: #ef8f8f;
}

.hljs-punctuation,
.hljs-meta,
.hljs-operator,
.hljs-subst,
.hljs-doctag,
.hljs-template-variable,
.hljs-selector-attr {
  color: #efbf8f;
}

.hljs-type {
  color: #efef8f;
}

.hljs-tag,
.hljs-title,
.hljs-selector-class,
.hljs-selector-id {
  color: #bfef8f;
}

.hljs-string,
.hljs-regexp,
.hljs-addition {
  color: #8fef8f;
}

.hljs-class,
.hljs-property {
  color: #8fefbf;
}

.hljs-name,
.hljs-selector-tag {
  color: #8fefef;
}

.hljs-keyword,
.hljs-built_in {
  color: #8fbfef;
}

.hljs-section,
.hljs-bullet {
  color: #8f8fef;
}

.hljs-selector-pseudo {
  color: #bf8fef;
}

.hljs-variable,
.hljs-params,
.hljs-attr,
.hljs-attribute {
  color: #ef8fef;
}

.hljs-symbol,
.hljs-link {
  color: #ef8fbf;
}

.hljs-strong,
.hljs-literal,
.hljs-title {
  font-weight: bold;
}

.hljs-emphasis {
  font-style: italic;
}

/* Skeleton Loader Styles */
.skeleton-loader {
  background: var(--vscode-editor-background, #1e1e22);
  border-radius: 8px;
  padding: 16px;
  margin: 8px 0;
  border: 1px solid var(--vscode-widget-border, #333);
}

.skeleton-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}

.skeleton-content {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.skeleton-line {
  height: 12px;
  background: linear-gradient(90deg, 
    var(--vscode-editor-background, #1e1e22) 0%,
    var(--vscode-input-background, #333) 50%,
    var(--vscode-editor-background, #1e1e22) 100%
  );
  border-radius: 6px;
  background-size: 200px 100%;
  background-position: -200px 0;
  animation: skeleton-pulse 1.5s ease-in-out infinite;
}

.skeleton-line-short {
  width: 30%;
}

.skeleton-line-medium {
  width: 60%;
}

.skeleton-line-long {
  width: 80%;
}

.skeleton-line-full {
  width: 100%;
}

@keyframes skeleton-pulse {
  0% {
    background-position: -200px 0;
  }
  100% {
    background-position: calc(200px + 100%) 0;
  }
}`;
